version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_gesuq
    restart: always
    environment:
      POSTGRES_DB: gesuq
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
